name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install -g purescript
    - run: npm install -g spago
    - name: build
      run: |
        spago -x test.dhall test